channels:
- conda-forge
dependencies:
- python=3.9.13
- numpy=1.23.3
- pytorch=1.12.1
- tqdm=4.64.1
- more-itertools=8.14.0
- transformers=4.21.1
- ffmpeg-python=0.2.0
- pip=22.1.2
- pip:
  - rpaframework==17.0.1
  - git+https://github.com/openai/whisper.git